#include "base_types.c"
#include "base_memory.c"
#include "base_math.c"
#include "base_strings.c"
#include "base_tctx.c"
#include "base_value_intern.c"
#include "base_string_pattern.c"
#include "base_text_edit.c"
